import {Accordion, AccordionItem} from "@nextui-org/react";

function RecRedesDD() {
  
  return (
    <div >
        <div className="container m-8 rounded-2xl mx-auto flex flex-col md:flex-row items-center justify-center md:justify-between p-8">
            <div className="md:w-1/3">
                
                <h1 className="text-4xl font-bold text-center text-primary-focus pr-4">Mais sobre as redes</h1>
                <p className="text-lg font-slate-500 text-center mt-4 pr-4">Você consegue imaginar o uso das redes sociais associados à educação? Vamos conhecer algumas redes e explorar seu potencial para atividades pedagógicas.</p>
                
            </div>
            <div className="w-full md:w-2/3 mt-8 md:mt-0">
              
                <Accordion variant='bordered'>
                    <AccordionItem key="1" aria-label="Accordion 1" title="Instagram">
                        <p className="text-slate-800 py-2">O Instagram é uma rede social cujo conteúdo é fortemente visual, isto é, fotos e vídeos curtos. Os usuários podem inserir efeitos e legendas nos vídeos, assim como fazer um breve texto associado ao material postado.</p>
                        <p className="text-slate-800 py-2">A rede social é bem fácil de usar e possui diversos recursos para criação e organização de conteúdo. Para conhecer alguns recursos que o Instagram possui e para saber como usá-los clique {''}<a href="https://www.google.com/url?q=https%3A%2F%2Feducapes.capes.gov.br%2Fbitstream%2Fcapes%2F583194%2F1%2FManual%2520Interativo%2520de%2520Utiliza%25C3%25A7%25C3%25A3o%2520do%2520Instagram%2520como%2520Ferramenta%2520Pedag%25C3%25B3gica.pdf&sa=D&sntz=1&usg=AOvVaw3mO2Q01faBymcUHdoOTO7b" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} para um guia completo ou {''}<a href="https://drive.google.com/file/d/1kV46FlOFcD8jzYtEpuMyd0QtZvVzfLsB/view?usp=sharing" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} para um guia resumido.</p>
                        <p className="text-slate-800 py-2">O Instagram também pode ser um poderoso aliado para as atividades em sala de aula. Confira {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fdesafiosdaeducacao.grupoa.com.br%2Fcomo-usar-instagram-em-sala-de-aula%2F&sa=D&sntz=1&usg=AOvVaw05daLa7_KjU8gdlS76JfHc" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} algumas ideias para o uso desta ferramenta com os alunos.</p>
                    </AccordionItem>
                    
                    <AccordionItem key="2" aria-label="Accordion 2" title="Facebook">
                        <p className="text-slate-800 py-2">Atualmente, o Facebook é a maior rede social do planeta, isto é, a que possui o maior número de usuários. A rede está estruturada na forma de páginas, onde cada usuário possui seu espaço, e nele pode postar e compartilhar fotos, vídeos, textos e gifs. Outros usuários podem se adicionar como amigos ou “curtir” e “seguir” páginas de seu interesse.</p>
                        <p className="text-slate-800 py-2">O Facebook é fácil de usar e apresenta diversos tipos de ferramentas e recursos. Para aprender a usar esta rede social você pode assistir um vídeo instrutivo {''}<a href="https://www.youtube.com/watch?v=BszYeoeiHF0" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} ou ler um tutorial completo {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fwww.mlabs.com.br%2Fblog%2Ffacebook%2F&sa=D&sntz=1&usg=AOvVaw3_YMFFkOSzUTgBkVwDb22T" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}.</p>
                        <p className="text-slate-800 py-2">O Facebook pode ser usado em sala de aula para ajudar a criar aulas e atividades mais interativas e desafiadoras que aumentam o engajamento do estudante. Você pode conferir algumas inspirações clicando {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fclaricemenezes.com.br%2F2017%2F01%2F20%2F5-maneiras-de-usar-o-facebook-na-sala-de-aula%2F&sa=D&sntz=1&usg=AOvVaw3cZVOHltigQQ_3EzlAn9r0" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}, {''}<a href="https://drive.google.com/file/d/1kV46FlOFcD8jzYtEpuMyd0QtZvVzfLsB/view?usp=sharing" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Feducador.brasilescola.uol.com.br%2Festrategias-ensino%2Ffacebook-na-sala-aula.htm&sa=D&sntz=1&usg=AOvVaw0plK78YjgSjSmkQTdEQxJA" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}. O Facebook é uma ferramenta que pode propiciar muitos benefícios para a sala de aula, clique {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fcanaldoensino.com.br%2Fblog%2F50-razoes-para-usar-o-facebook-em-sua-sala-de-aula&sa=D&sntz=1&usg=AOvVaw1oq1CrOW0DFpEexREY4Uzt" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e confira algumas razões para usá-lo.</p>
                    </AccordionItem>
                    
                    <AccordionItem key="3" aria-label="Accordion 3" title="Youtube">
                        <p className="text-slate-800 py-2">O YouTube é a segunda maior rede social do planeta, e um dos motivos deste sucesso é que o material utilizado para criação e divulgação de conteúdos é apenas vídeos. Os usuários possuem canais onde podem postar conteúdo produzido por eles próprios e criar e organizar playlists, ou listas com conteúdos de outros canais. Os usuários podem se inscrever nos canais uns dos outros. A criação de vídeos é por conta do usuário, o YouTube funciona como (um repositor).</p>
                        <p className="text-slate-800 py-2">O YouTube é uma plataforma fácil de usar, tanto para quem cria quanto para quem busca conteúdo. Se você usa a rede para buscar conteúdo, pode usar {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fwww.tecmundo.com.br%2Ftutorial%2F23898-youtube-15-dicas-para-facilitar-a-busca-de-videos.htm%23%3A~%3Atext%3DAo%2520usar%2520o%2520s%25C3%25ADmbolo%2520%25E2%2580%259C%252B%25E2%2580%259D%2Cdigite%2520%25E2%2580%259CTecmundo%2520%252Ban%25C3%25A1lise%25E2%2580%259D.&sa=D&sntz=1&usg=AOvVaw1e3je1uI0q9wixtp9Sz2w1" target="blank" className="underline text-blue-700 hover:text-purple-900">estas</a>{''} dicas para otimizar sua pesquisa. Caso você queira criar um canal para postar seus vídeos ou organizar playlists, você pode assistir a {''}<a href="https://www.youtube.com/watch?v=8s90WykP-F0" target="blank" className="underline text-blue-700 hover:text-purple-900">esse</a>{''} vídeo. Se você tem interesse em produzir vídeos (ou desafiar seus estudantes para tal), confira {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fnfe.io%2Fblog%2Fmarketing%2Fmelhores-programas-para-editar-videos%2F&sa=D&sntz=1&usg=AOvVaw22MqpDddDFVDF61Vd8n-8c" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} uma lista de programas para edição.</p>
                        <p className="text-slate-800 py-2">Por ser uma plataforma de vídeos, o YouTube é uma ferramenta muito útil de apoio ao professor. Você pode clicar {''}<a href="https://drive.google.com/file/d/10Dzs_wE0XpihQXpHk5jOVl2TRK8ciZvP/view?usp=sharing" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fcanaltech.com.br%2Feducacao%2Fdia-da-educacao-como-o-youtube-se-tornou-uma-verdadeira-sala-de-aula-183485%2F&sa=D&sntz=1&usg=AOvVaw2sJPbT1knTu1M-HGn4id2M" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} para descobrir algumas razões pelas quais a rede é uma das favoritas dos professores. Confira algumas dicas e ideias para uso desta rede em sala de aula neste texto {''}<a href="https://www.google.com/url?q=https%3A%2F%2Ffilmora.wondershare.com.br%2Fvideo-editing-tips%2Ftips-for-using-youtube-in-classroom.html&sa=D&sntz=1&usg=AOvVaw0POxLYum0pzCtFKBj5LoWZ" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e também <a href="https://www.youtube.com/watch?v=Uia454rWe2s" target="blank" className="underline text-blue-700 hover:text-purple-900">neste</a>{''} vídeo e {''}<a href="https://www.youtube.com/watch?v=NyZ_3d4cORs" target="blank" className="underline text-blue-700 hover:text-purple-900">neste</a>{''} vídeo.</p>
                    </AccordionItem>

                    <AccordionItem key="4" aria-label="Accordion 3" title="Twitter">
                        <p className="text-slate-800 py-2">O Twitter é uma famosa rede social no formato de microblog, isso é, permite rápida atualização de conteúdo em sequência. Seu principal tipo de post é na forma de texto com o limite de 280 caracteres, mas também podemos postar imagens, vídeos e gifs. A rede está estruturada em perfis, onde cada usuário possui o seu e pode seguir aqueles que mais interessam.</p>
                        <p className="text-slate-800 py-2">Como todas as redes sociais listadas aqui, o Twitter também é fácil de usar, possui diversas ferramentas e funções intuitivas. Você pode acessar tutoriais de criação de conta e uso da rede {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fneilpatel.com%2Fbr%2Fblog%2Fcomo-usar-twitter%2F&sa=D&sntz=1&usg=AOvVaw3fYBtfl9IkCkIQUkWUVISQ" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fhelp.twitter.com%2Fpt%2Fusing-twitter&sa=D&sntz=1&usg=AOvVaw0ZOB0-hvlfXs1hp-5r9cJ7" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}. Para entender melhor o funcionamento da rede, sua dinâmica e códigos, você pode acessar {''}<a href="https://www.google.com/url?q=https%3A%2F%2Ftecnoblog.net%2Fresponde%2Fcomo-usar-o-twitter%2F&sa=D&sntz=1&usg=AOvVaw2Qs6fnAgNLDq19xM9Tnr2G" target="blank" className="underline text-blue-700 hover:text-purple-900">este</a>{''} texto.</p>
                        <p className="text-slate-800 py-2">Esta rede também é uma ótima escolha para apoiar o trabalho do professor em sala de aula. Você pode se inspirar com algumas ideias {''}<a href="https://www.google.com/url?q=https%3A%2F%2Funimontes.br%2F25-maneiras-de-usar-o-twitter-em-sala-de-aula-e-conquistar-seus-alunos%2F&sa=D&sntz=1&usg=AOvVaw0HdiWxEbA38yt2XSYmebd4" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}, {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fwww.universia.net%2Fbr%2Factualidad%2Forientacion-academica%2Fprofessor-10-maneiras-usar-o-twitter-na-sala-aula-1123912.html&sa=D&sntz=1&usg=AOvVaw3tdQCRe2Qw_p0sDEgVUDh1" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fcanaldoensino.com.br%2Fblog%2F10-maneiras-de-usar-o-twitter-em-sala-de-aula&sa=D&sntz=1&usg=AOvVaw3BqzjWFH01ygEri3y_qcY1" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}.</p>
                    </AccordionItem>

                    <AccordionItem key="5" aria-label="Accordion 3" title="TikTok">
                    <p className="text-slate-800 py-2">O TikTok é uma rede social relativamente nova no mercado e que tem crescido rapidamente. Seu grande atrativo é o formato dos posts, que são vídeos de até 15 segundos acompanhados de músicas e cheios de efeitos. Esta rede tornou-se um fenômeno entre os jovens. Os usuários criam um perfil e podem seguir outros usuários. Atualmente a rede só pode ser utilizada em celulares.</p>
                    <p className="text-slate-800 py-2">Para auxiliar você a criar seu perfil e navegar por esta rede, você pode ler {''}<a href="https://www.google.com/url?q=https%3A%2F%2Ftecnoblog.net%2Fresponde%2Fcomo-usar-o-tiktok%2F&sa=D&sntz=1&usg=AOvVaw03ch9vTJnEPByIuVx0kVWG" target="blank" className="underline text-blue-700 hover:text-purple-900">este turorial</a>{''} ou assistir a {''}<a href="https://www.youtube.com/watch?v=N0PN1z-y8pc" target="blank" className="underline text-blue-700 hover:text-purple-900">este vídeo</a>{''}, que explica desde a criação de conta até a criação e postagem de conteúdo.</p>
                    <p className="text-slate-800 py-2">O TikTok traz alguns desafios para o educador, pois, além de ser uma novidade cheia de funcionalidades, como transmitir um conteúdo de maneira efetiva em pouco tempo? Por incrível que pareça, alunos e professores recorreram a esta rede, que agora também é sucesso na educação. Surgiu então a chamada “pedagogia do TikTok” (você pode ler mais sobre isso {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fdesafiosdaeducacao.grupoa.com.br%2Fpedagogia-do-tiktok-em-aula%2F&sa=D&sntz=1&usg=AOvVaw1pBbaE8dgQb5fvuOYV6uPP" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}) e a integração da rede social com a educação já é uma realidade (como descrito pelo {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fcer.sebrae.com.br%2Fblog%2Fda-para-usar-o-tiktok-na-educacao-entenda-as-caracteristicas-do-app-e-como-usa-lo-na-educacao%2F&sa=D&sntz=1&usg=AOvVaw2OtsW_-Yug_su_KLyQzHKe" target="blank" className="underline text-blue-700 hover:text-purple-900">SEBRAE</a>{''}).</p>
                    <p className="text-slate-800 py-2">Para inspirar você a usar esta ferramenta em sala de aula, separamos {''}<a href="https://www.youtube.com/watch?v=FeGVfh-i8W0" target="blank" className="underline text-blue-700 hover:text-purple-900">este</a>{''} vídeo e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fblog.lyceum.com.br%2Fpedagogia-tik-tok%2F&sa=D&sntz=1&usg=AOvVaw1rM2lwIRRva6CZCdUc6IJt" target="blank" className="underline text-blue-700 hover:text-purple-900">este</a>{''} texto, ambos cheios de dicas para usar este app.</p>
                    </AccordionItem>

                    <AccordionItem key="6" aria-label="Accordion 3" title="Whatzapp">
                    <p className="text-slate-800 py-2">O aplicativo de mensagens mais utilizado no Brasil também se enquadra como uma rede social. A ferramenta foi criada visando a troca de mensagens textuais entre usuários de celulares, porém, com o tempo, agora é possível compartilhar fotos, vídeos e gifs. Para utilizar a rede social é necessário um número de telefone e um aparelho celular. Pode-se acessar o Whatsapp pelo computador como uma forma de suporte ao celular.</p>
                    <p className="text-slate-800 py-2">O Whatsapp é fácil de usar, porém, mesmo sendo um grande conhecido, apresenta funcionalidades que alguns usuários podem não conhecer como formatar características textuais das mensagens ou criar linhas de transmissão com contatos. Apresentamos {''}<a href="https://www.google.com/url?q=https%3A%2F%2Ftecnoblog.net%2Fresponde%2Fcomo-usar-o-whatsapp%2F&sa=D&sntz=1&usg=AOvVaw3NiL6jF1m_tV119qzybpXb" target="blank" className="underline text-blue-700 hover:text-purple-900">este texto</a>{''} com um tutorial detalhado sobre o uso desta rede.</p>
                    <p className="text-slate-800 py-2">Dentro da sala de aula, o Whatsapp pode servir tanto para auxiliar o professor com questões associadas ao conteúdo assim como otimizar a comunicação com os estudantes. Separamos alguns textos que trazem sugestões de uso do aplicativo dentro da escola e da sala de aula, você pode conferir {''}<a href="https://drive.google.com/file/d/1o7nLEQ_mYADXW4v3LlxsiipF9PgM0CCa/view?usp=sharing" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}, {''}<a href="https://www.google.com/url?q=https%3A%2F%2Ftecnoblog.net%2Fresponde%2F8-dicas-do-whatsapp-para-escolas-professores-e-educadores%2F&sa=D&sntz=1&usg=AOvVaw07fAfsExRtO8_PnTvCtVgh" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''} e {''}<a href="https://www.google.com/url?q=https%3A%2F%2Fcanaldoensino.com.br%2Fblog%2Fcomo-usar-o-whatsapp-em-sala-de-aula&sa=D&sntz=1&usg=AOvVaw1el3pt3RBg6WBd5Uj-2D51" target="blank" className="underline text-blue-700 hover:text-purple-900">aqui</a>{''}.</p>
                    <p className="text-slate-800 py-2">O uso do Whatsapp em sala de aula é possível, desde que feito com sabedoria e moderação, uma vez que envolve uma ferramenta de comunicação direta entre alunos e professores. Para evitar transtornos, é possível definir configurações no aplicativo, veja {''}<a href="https://www.youtube.com/watch?v=vWZj5FbxmiQ" target="blank" className="underline text-blue-700 hover:text-purple-900">neste vídeo</a>{''}.</p>
                    </AccordionItem>
                </Accordion>
            </div>
            </div>
    </div>
  );
}

export default RecRedesDD;




